# pyproject.toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MA2006B"
version = "0.1.0"
description = "Paquete de apoyo para el curso MA2006B Uso de álgebras modernas para seguridad y criptografía"
authors = [
  { name = "Raul Gomez", email = "rgomez@tec.mx" }
]
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "matplotlib",
  "scipy",
  "ipython",
  "cryptography",
  "pycryptodome",
  "pyzmq",
  "tornado",
  "traitlets",
  "pyyaml>=6.0.3",
  "jupyter>=1.1.1",
]

[project.scripts]
ecc_test = "cryptocalc.ecc_test:main"
rsa_cryptography_test = "cryptocalc.rsa_cryptography_test:main"
